name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "better-draft"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: RelWithDebInfo
          export-pdb: true
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}

  draft:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: ['package']

    steps:
      - name: Find Version (mod.json) and Changelog (changelog.md)
        id: version
        run: echo version=$(jq -r .version mod.json) >> $GITHUB_OUTPUT

      - name: Find Changelog (changelog.md)
        id: changelog
        run: echo changelog=$(awk "/## ${{ steps.version.outputs.version }}/{flag=1; next} /##/{flag=0} flag" changelog.md | sed -e :a -e '/^\n*$/{$d;N;ba}')

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: Build Output
          path: build-output

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build-output/*.geode
            build-output/*.pdb
          tag_name: ${{ github.event.head_commit.message }}
          name: ${{ github.event.head_commit.message }}
          body: ${{ steps.changelog.outputs.changelog }}
